/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view.member;

import app.controller.BarangayController;
import app.controller.CityController;
import app.controller.ProvinceController;
import app.model.ComboBoxItem;
import javax.swing.JOptionPane;

/**
 *
 * @author EngkoiZidac
 */
public class UpdateAddressProv extends javax.swing.JDialog {

    public static UpdateMember frmParent;
    private static int ComboBoxCityId, ComboBoxProvinceId, ComboBoxBarangayId;
    BarangayController BarangayController = new BarangayController();
    CityController CityController = new CityController();
    ProvinceController ProvinceController = new ProvinceController();

    public UpdateAddressProv(UpdateMember parent, boolean modal) {
        frmParent = parent;
        this.setModal(modal);
        initComponents();
        setLocationRelativeTo(this);
        ProvinceController.PopulateComboBoxData(ComboProvince);
        CityController.PopulateComboBoxData(ComboCity, ComboBoxProvinceId);
        BarangayController.PopulateComboBoxData(ComboBarangay, ComboBoxCityId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboProvince = new javax.swing.JComboBox<>();
        ComboCity = new javax.swing.JComboBox<>();
        ComboBarangay = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cmdok = new javax.swing.JButton();
        cmdexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Upddate Provincial Address");

        ComboProvince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboProvinceActionPerformed(evt);
            }
        });

        ComboCity.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                ComboCityHierarchyChanged(evt);
            }
        });
        ComboCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCityActionPerformed(evt);
            }
        });
        ComboCity.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                ComboCityVetoableChange(evt);
            }
        });

        ComboBarangay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBarangayActionPerformed(evt);
            }
        });

        jLabel28.setForeground(new java.awt.Color(153, 0, 153));
        jLabel28.setText("Province");

        jLabel29.setForeground(new java.awt.Color(153, 0, 153));
        jLabel29.setText("Municipality/City");

        jLabel30.setForeground(new java.awt.Color(153, 0, 153));
        jLabel30.setText("Barangay");

        cmdok.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/movedown_1.png"))); // NOI18N
        cmdok.setMnemonic('O');
        cmdok.setText("Ok");
        cmdok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdokActionPerformed(evt);
            }
        });

        cmdexit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/remove.png"))); // NOI18N
        cmdexit.setMnemonic('C');
        cmdexit.setText("Cancel");
        cmdexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdok, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdexit, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ComboCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBarangay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel28)
                    .addComponent(ComboProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel29)
                    .addComponent(ComboCity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel30)
                    .addComponent(ComboBarangay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdok)
                    .addComponent(cmdexit))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboProvinceActionPerformed
        ComboBoxCityId = 0;
        ComboBoxProvinceId = 0;
        ComboBoxBarangayId = 0;
        try {
            ComboBoxItem item = (ComboBoxItem) ComboProvince.getSelectedItem();
            ComboBoxProvinceId = item.getId();
            CityController.PopulateComboBoxData(ComboCity, ComboBoxProvinceId);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ComboProvinceActionPerformed

    private void ComboCityHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_ComboCityHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCityHierarchyChanged

    private void ComboCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCityActionPerformed
        ComboBoxCityId = 0;
        try {
            ComboBoxItem item = (ComboBoxItem) ComboCity.getSelectedItem();
            ComboBoxCityId = item.getId();
            BarangayController.PopulateComboBoxData(ComboBarangay, ComboBoxCityId);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ComboCityActionPerformed

    private void ComboCityVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_ComboCityVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCityVetoableChange

    private void ComboBarangayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBarangayActionPerformed
        ComboBoxBarangayId = 0;
        try {
            ComboBoxItem item = (ComboBoxItem) ComboBarangay.getSelectedItem();
            ComboBoxBarangayId = item.getId();
        } catch (Exception e) {
        }
        ///  System.out.println(ComboBoxBarangayId);
    }//GEN-LAST:event_ComboBarangayActionPerformed

    private void cmdokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdokActionPerformed
        if (ComboProvince.getSelectedIndex() == 0
            || ComboCity.getSelectedIndex() == 0
            || ComboBarangay.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please fill-up the required fields!");
        } else {
            frmParent.populateComboAddressProv(ComboProvince.getSelectedItem().toString(), ComboCity.getSelectedItem().toString(), ComboBarangay.getSelectedItem().toString(), ComboBoxProvinceId, ComboBoxCityId, ComboBoxBarangayId);
            this.dispose();
        }
        //System.out.println(ComboBoxBarangayId);
    }//GEN-LAST:event_cmdokActionPerformed

    private void cmdexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdexitActionPerformed
        this.dispose();
    }//GEN-LAST:event_cmdexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateAddressProv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateAddressProv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateAddressProv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateAddressProv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateAddressProv dialog = new UpdateAddressProv(frmParent, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBarangay;
    private javax.swing.JComboBox<String> ComboCity;
    private javax.swing.JComboBox<String> ComboProvince;
    private javax.swing.JButton cmdexit;
    private javax.swing.JButton cmdok;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    // End of variables declaration//GEN-END:variables
}
